### ISSUE TITLE
不打开弹窗翻译，侧边栏不能自动翻译[Feature]

### ISSUE THREAD

**Issue by Syzygy33** [windingwind/zotero-pdf-translate#29]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by VoidR** [comment]
I also encountered this problem, Actually, the result was obtained, it just didn't show up.

**Comment by windingwind** [comment]
Fixed in the v0.3.0

**Comment by RemnantCloude** [comment]
I still have this problem in v0.3.4 (zotero v6.0.2). It doesn't work even when I click the "Translate" botton.

**Comment by windingwind** [comment]
see #17 and could you please follow the same debug steps:

go to Help->Debug Output Logging->View Output. 
Open your pdf. 
Select some text after the debug window is opened and paste the logs in this issue. 

With debug logs, I can find out what's going on with your Zotero.

**Comment by RemnantCloude** [comment]
您好，您的邮件我已收到，会尽快查看。by邓臣成/残云

**Comment by RemnantCloude** [comment]
Thanks for your reply. This add-on works when I reboot my computer and zotero today. I tried reinstalling the add-on to find the bug and it still works, so this bug looks like just an accidental event.

**Comment by windingwind** [comment]
Happy to hear that.

I'll close this issue. If you still have the same problem, feel free to open it again.

**Comment by zhou201505013** [comment]
I still have this problem in v0.5.2 Zotero v6.0.4. The log is shown below


(4)(+0028364): SELECT IA.itemID FROM itemAttachments IA NATURAL JOIN items I LEFT JOIN itemData ID ON (IA.itemID=ID.itemID AND fieldID=13) LEFT JOIN itemDataValues IDV ON (ID.valueID=IDV.valueID) WHERE parentItemID=? AND linkMode NOT IN (3) AND IA.itemID NOT IN (SELECT itemID FROM deletedItems) ORDER BY contentType='application/pdf' DESC, value=? DESC, dateAdded ASC [226, 'http://arxiv.org/abs/2108.07258']

(3)(+0000003): Viewing attachment 1/RH8W88TH

(3)(+0000002): Opening D:\Zotero\storage\RH8W88TH\Bommasani 等。 - 2021 - On the Opportunities and Risks of Foundation Model.pdf

(3)(+0000001): Notifier.trigger('open', 'file', [222]) called [observers: 6]

(3)(+0000008): Notifier.trigger('add', 'tab', [tab-1PUITFRj], {"tab-1PUITFRj":{"itemID":222}}) called [observers: 5]

(3)(+0000005): Notifier.trigger('select', 'tab', [tab-1PUITFRj], {"tab-1PUITFRj":{"type":"reader"}}) called [observers: 5]

(3)(+0000009): ZoteroPDFTranslate: open attachment event detected.

(3)(+0000001): ZoteroPDFTranslate: Update Translate Panels

(3)(+0000001): ZoteroPDFTranslate.bindAddToNote

(3)(+0000039): Refreshing item box

(3)(+0000048): ZoteroPDFTranslate: open window event detected.

(3)(+0000223): itemTree.render(). Displaying Item Tree

(3)(+0000006): Getting contents of D:\Zotero\storage\RH8W88TH\.zotero-pdf-state

(3)(+0000067): ZoteroPDFTranslate: buildSideBarPanel

(3)(+0000008): ZoteroPDFTranslate: updateSideBarPanelMenu

(3)(+0005553): ZoteroPDFTranslate: onTranslate. language disable=false

(3)(+0000001): ZoteroPDFTranslate: updateSideBarPanelMenu

(3)(+0000002): TypeError: can't access dead object updateResults@chrome://zoteropdftranslate/content/scripts/index.js:1293:11 callTranslate/<@chrome://zoteropdftranslate/content/scripts/index.js:1878:9 __async/<@chrome://zoteropdftranslate/content/scripts/index.js:44:13 __async@chrome://zoteropdftranslate/content/scripts/index.js:28:12 callTranslate@chrome://zoteropdftranslate/content/scripts/index.js:1860:14 onSelect/<@chrome://zoteropdftranslate/content/scripts/index.js:673:17 __async/<@chrome://zoteropdftranslate/content/scripts/index.js:44:13 __async@chrome://zoteropdftranslate/content/scripts/index.js:28:12 onSelect@chrome://zoteropdftranslate/content/scripts/index.js:651:14 updateTranslatePanel/</<@chrome://zoteropdftranslate/content/scripts/index.js:909:13

(3)(+0000001): ZoteroPDFTranslate: updatePopupStyle

**Comment by windingwind** [comment]
@zhou201505013 
Could you please check the settings in Edit->Preferences->PDF Translate->General->Functions and see if `Automatic Translation` is disabled.

**Comment by zhou201505013** [comment]
> @zhou201505013 Could you please check the settings in Edit->Preferences->PDF Translate->General->Functions and see if `Automatic Translation` is disabled.

The `Automatic Translation` is enabled. My settings is shown below.
![image](https://user-images.githubusercontent.com/39976863/163754514-bbf3c5eb-5f9f-47d3-8288-9f899f7c85ca.png)

**Comment by zhou201505013** [comment]
I just found that after chose some text i have to right click and chose `copy` to translate. If I enable the popup, i just need to chose the text and the translation will show up in the side bar.

**Comment by windingwind** [comment]
Seem like your debug logs above are not created in a fresh new start of Zotero. The network request is not triggered, which means you selected the same text before the log.

I guess this is caused by a slow network. The translations are not ready until you clicked the copy button.

**Comment by zhou201505013** [comment]
> Seem like your debug logs above are not created in a fresh new start of Zotero. The network request is not triggered, which means you selected the same text before the log.
> 
> I guess this is caused by a slow network. The translations are not ready until you clicked the copy button.

You are right, thanks for your time
