### ISSUE TITLE
[Bug] The result of the translation is showing Portuguese (Portugal) instead of Portuguese (Brazil)

### ISSUE THREAD

**Issue by lbarrios1** [windingwind/zotero-pdf-translate#997]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you checked the FAQ (https://github.com/windingwind/zotero-pdf-translate/issues/6)?

- [X] I have checked the FAQ

### Are you using the latest Zotero and the latest plugin?

- [X] I have confirmed I'm using the latest Zotero and the latest plugin

### Environment

OS: Windows 11 Home
Zotero Version: 7.0.9 (64-bit)
Plugin Version: 2.0.5

### Describe the bug

I configured the plugin to translate from English (United States) to Portuguese (Brazil). However, the translation result is showing as Portuguese (Portugal).

This is proven by testing the Google Translate tool itself, which shows the difference in spelling between Portuguese (Brazilian) and Portuguese (Portugal) words.

### Debug Output

[debug output.txt](https://github.com/user-attachments/files/17607183/debug.output.txt)

### Anything else?

![print4](https://github.com/user-attachments/assets/656e0c1f-42fa-4c9b-a730-7b79cbdd71e4)
![print3](https://github.com/user-attachments/assets/d7efc2ec-56b8-4d2c-9802-06b988360619)
![print2](https://github.com/user-attachments/assets/09e05eb5-7c4c-4756-a889-623bc5fb4a1a)
![print1](https://github.com/user-attachments/assets/e69a98f6-e1a0-4e32-bc81-b05e22245424)

**Comment by windingwind** [comment]
Google Translate uses `pt` for Portuguese (Brazil), instead of `pt-BR`, and `pt-PT` for Portuguese (Portugal). It should be fine if you choose the option `Portuguese` if you are on old versions.

The latest release should fix this.

**Comment by lbarrios1** [comment]
@windingwind, thank you for your attention on this matter.

I'm afraid that the bug is still not fixed.

I updated the plugin to the most updated version (2.0.12).

It doesn't matter if I choose `Google (API)` engine or other engine (e.g., `DeepL (Free Plan)`), and it doesn't matter if I choose '`Portuguese`' or '`Portuguese (Brazil)`' as output languages, the result of the translation is still showing in Portuguese (Portugal).


![zotero-print1](https://github.com/user-attachments/assets/9c215fc1-4612-4569-b4c3-b05938814a0f)

![zotero-print2](https://github.com/user-attachments/assets/9bd93776-6d6c-4ea0-9b97-5321bb20fb3a)

![zotero-print3](https://github.com/user-attachments/assets/bc49149d-4db2-4e00-bcb5-fecd7fe77c12)

[debug output.txt](https://github.com/user-attachments/files/17983265/debug.output.txt)

**Comment by windingwind** [comment]
Thanks for the feedback.

For Google, I really have no idea what's going on there. Since this is a somehow _hacked_ version of the API used by the Google Translate website, there are a lot of guesses that Google provides degraded results on purpose for this kind of usage.

The issue with DeepL and DeepLX should be fixed now. Please try again.

**Comment by windingwind** [comment]
I keep this issue open for now:)
